export let ataques = {
  debiles: [
    { id: 'mirada_cuqui', nombre: 'Mirada Cuqui', tipo: 'planta', icono: 'leaf', puntos_dano: 10, segundos_enfriamiento: 0.8, incremento_energia: 6 },
    { id: 'culo_pompa', nombre: 'Culo en Pompa', tipo: 'planta', icono: 'leaf', puntos_dano: 5, segundos_enfriamiento: 0.5, incremento_energia: 5 },
    { id: 'fogonazo', nombre: 'Fogonazo', tipo: 'fuego', icono: 'flame', puntos_dano: 10, segundos_enfriamiento: 1.2, incremento_energia: 7 },
    { id: 'ascuas', nombre: 'Ascuas', tipo: 'fuego', icono: 'flame', puntos_dano: 6, segundos_enfriamiento: 0.7, incremento_energia: 5 },
    { id: 'pistola_agua', nombre: 'Pistola de Agua', icono: 'water', tipo: 'agua', puntos_dano: 5, segundos_enfriamiento: 0.6, incremento_energia: 5 },
    { id: 'mordisquito', nombre: 'Mordisquito', icono: 'flask', tipo: 'veneno', puntos_dano: 6, segundos_enfriamiento: 0.5, incremento_energia: 4 },
    { id: 'chispa', nombre: 'Chispa', tipo: 'electrico', icono: 'flash', puntos_dano: 6, segundos_enfriamiento: 0.7, incremento_energia: 9 },
    { id: 'voltiazo', nombre: 'Voltiazo', tipo: 'electrico', icono: 'flash', puntos_dano: 20, segundos_enfriamiento: 2.3, incremento_energia: 25 },
    { id: 'puya_venenosa', nombre: 'Puya Venenosa', tipo: 'veneno', icono: 'flask', puntos_dano: 10, segundos_enfriamiento: 0.8, incremento_energia: 7 },
    { id: 'destructor', nombre: 'Destructor', tipo: 'normal', icono: 'refresh-circle', puntos_dano: 7, segundos_enfriamiento: 0.6, incremento_energia: 6 },
    { id: 'cabezazo', nombre: 'Cabezazo', tipo: 'normal', icono: 'refresh-circle', puntos_dano: 12, segundos_enfriamiento: 1.1, incremento_energia: 10 },
    { id: 'confusion', nombre: 'Confusión', tipo: 'normal', icono: 'refresh-circle', puntos_dano: 20, segundos_enfriamiento: 1.6, incremento_energia: 15 },
    { id: 'aliento_fuego', nombre: 'Aliento de Fuego', tipo: 'fuego', icono: 'flame', puntos_dano: 11, segundos_enfriamiento: 0.9, incremento_energia: 8 },
    { id: 'alarido', nombre: 'Alarido', icono: 'flask', tipo: 'veneno', puntos_dano: 12, segundos_enfriamiento: 1.1, incremento_energia: 12 },
    { id: 'burbuja', nombre: 'Burbuja', icono: 'water', tipo: 'agua', puntos_dano: 12, segundos_enfriamiento: 1.2, incremento_energia: 14 },
    { id: 'corte', nombre: 'Corte', tipo: 'normal', icono: 'refresh-circle', puntos_dano: 5, segundos_enfriamiento: 0.6, incremento_energia: 8 },
    { id: 'bostezo', nombre: 'Bostezo', tipo: 'normal', icono: 'refresh-circle', puntos_dano: 0, segundos_enfriamiento: 1.7, incremento_energia: 15 }
  ],
  fuertes: [
    { id: 'pucheritos', nombre: 'Pucheritos', tipo: 'planta', puntos_dano: 80, segundos_enfriamiento: 17, gasto_energia: 33 },
    { id: 'ira_animal', nombre: 'Ira Animal', tipo: 'planta', puntos_dano: 150, segundos_enfriamiento: 36, gasto_energia: 100 },
    { id: 'rayo_solar', nombre: 'Rayo Solar', tipo: 'planta', puntos_dano: 180, segundos_enfriamiento: 32, gasto_energia: 100 },
    { id: 'lluvia_esporas', nombre: 'Lluvia de Esporas', tipo: 'planta', puntos_dano: 90, segundos_enfriamiento: 15, gasto_energia: 50 },
    { id: 'erupcion_volcanica', nombre: 'Erupción Volcánica', tipo: 'fuego', puntos_dano: 80, segundos_enfriamiento: 12, gasto_energia: 33 },
    { id: 'lluvia_fuego', nombre: 'Lluvia de Fuego', tipo: 'fuego', puntos_dano: 150, segundos_enfriamiento: 30, gasto_energia: 100 },
    { id: 'hidro_bomba', nombre: 'Hidro Bomba', tipo: 'agua', puntos_dano: 130, segundos_enfriamiento: 3.3, gasto_energia: 100 },
    { id: 'golpe_helado', nombre: 'Golpe Helado', tipo: 'agua', puntos_dano: 90, segundos_enfriamiento: 3.1, gasto_energia: 50 },
    { id: 'carga_total', nombre: 'Carga Total', tipo: 'electrico', puntos_dano: 90, segundos_enfriamiento: 2.6, gasto_energia: 50 },
    { id: 'puno_trueno', nombre: 'Puño de Trueno', tipo: 'electrico', puntos_dano: 45, segundos_enfriamiento: 1.8, gasto_energia: 33 },
    { id: 'terremoto', nombre: 'Terremoto', tipo: 'veneno', puntos_dano: 120, segundos_enfriamiento: 3.6, gasto_energia: 100 },
    { id: 'onda_choque', nombre: 'Onda de Choque', tipo: 'veneno', puntos_dano: 110, segundos_enfriamiento: 3.2, gasto_energia: 100 },
    { id: 'hiperrayo', nombre: 'Hiperrayo', tipo: 'normal', puntos_dano: 150, segundos_enfriamiento: 3.8, gasto_energia: 100 },
    { id: 'brillo_magico', nombre: 'Brillo Mágico', tipo: 'normal', puntos_dano: 100, segundos_enfriamiento: 3.5, gasto_energia: 50 },
    { id: 'onda_certera', nombre: 'Onda Certera', tipo: 'normal', puntos_dano: 140, segundos_enfriamiento: 3.5, gasto_energia: 100 },
    { id: 'llamarada', nombre: 'Llamarada', tipo: 'fuego', puntos_dano: 140, segundos_enfriamiento: 4.2, gasto_energia: 100 },
    { id: '10000_voltios', nombre: '10.000 Voltios', tipo: 'electrico', puntos_dano: 90, segundos_enfriamiento: 2.6, gasto_energia: 50 },
    { id: 'premonicion', nombre: 'Premonición', tipo: 'normal', puntos_dano: 120, segundos_enfriamiento: 2.7, gasto_energia: 100 }
  ]
};
